<?php

// Kontroler za sve operacije vezane za iznajmljivanja.
require_once __DIR__.'/../servisi/Sesija.php';require_once __DIR__.'/../podaci/IznajmljivanjeRepozitorijum.php';require_once __DIR__.'/../podaci/VoziloRepozitorijum.php';require_once __DIR__.'/../podaci/KlijentRepozitorijum.php';require_once __DIR__.'/../podaci/AktivnostRepozitorijum.php';require_once __DIR__.'/../validacija/Validacija.php';require_once __DIR__.'/../model/Iznajmljivanje.php';require_once __DIR__.'/../model/StavkaIznajmljivanja.php';
class IznajmljivanjeKontroler
{
    public function index(): void { Sesija::zahtevajPrijavu();$filter=trim($_GET['filter']??'');$f=['status'=>$_GET['status']??'','klijentId'=>$_GET['klijentId']??'','voziloId'=>$_GET['voziloId']??'','datumOd'=>$_GET['datumOd']??'','datumDo'=>$_GET['datumDo']??'','minCena'=>$_GET['minCena']??'','maxCena'=>$_GET['maxCena']??''];$svi=(new IznajmljivanjeRepozitorijum())->dajSve($filter,$f);$str=max(1,(int)($_GET['str']??1));$po=10;$ukupno=count($svi);$brojStr=max(1,(int)ceil($ukupno/$po));$str=min($str,$brojStr);$redovi=array_slice($svi,($str-1)*$po,$po);$klijenti=(new KlijentRepozitorijum())->dajSve();$vozilaFilter=(new VoziloRepozitorijum())->dajSve();$poruka=Sesija::uzmiPoruku();require __DIR__.'/../pogledi/iznajmljivanja/index.php'; }
    // Kod dodavanja pravim model objekte i saljem ih repozitorijumu.
    public function dodaj(): void { Sesija::zahtevajPrijavu();$v=new VoziloRepozitorijum();$k=new KlijentRepozitorijum();$vozila=$v->dajSlobodna();$klijenti=$k->dajSve();$greska='';if($_SERVER['REQUEST_METHOD']==='POST'){$kid=(int)($_POST['klijentId']??0);$od=$_POST['datumOd']??'';$do=$_POST['datumDo']??'';$iz=$_POST['vozila']??[];if($kid<1||!$k->dajPoId($kid))$greska='Izaberite postojećeg klijenta.';if(!$greska)$greska=Validacija::datumOpseg($od,$do)??'';if(!$greska&&!$iz)$greska='Izaberite najmanje jedno vozilo.';if(!$greska)try{$mejl=Sesija::korisnik()['Mejl']??'';$klijent=$k->dajPoId($kid);$iznajmljivanje=new Iznajmljivanje(null,$klijent,$od,$do,'Aktivno');foreach($iz as $vid){$vozilo=$v->dajPoId((int)$vid);if(!$vozilo)throw new Exception('Izabrano vozilo nije pronađeno.');$iznajmljivanje->dodajStavku(new StavkaIznajmljivanja(null,$vozilo,$iznajmljivanje->brojDana(),$vozilo->cenaPoDanu,$iznajmljivanje->brojDana()*$vozilo->cenaPoDanu));}$id=(new IznajmljivanjeRepozitorijum())->dodaj($iznajmljivanje,$mejl);$this->log('Dodavanje','Iznajmljivanje',$id,'Kreiran ugovor');Sesija::postaviPoruku('Iznajmljivanje je uspešno kreirano.');header('Location: index.php?stranica=iznajmljivanje-detalji&id='.$id);exit;}catch(Throwable $e){$greska=$e->getMessage();}}require __DIR__.'/../pogledi/iznajmljivanja/dodaj.php'; }
    public function detalji(): void { Sesija::zahtevajPrijavu();$id=(int)($_GET['id']??0);$zapis=(new IznajmljivanjeRepozitorijum())->dajPoId($id);if(!$zapis){http_response_code(404);$greska='Iznajmljivanje nije pronađeno.';}$poruka=Sesija::uzmiPoruku();require __DIR__.'/../pogledi/iznajmljivanja/detalji.php'; }
    public function izmeni(): void { Sesija::zahtevajPrijavu();$id=(int)($_GET['id']??0);$repo=new IznajmljivanjeRepozitorijum();$zapis=$repo->dajPoId($id);if(!$zapis)die('Iznajmljivanje nije pronađeno.');if($zapis['Status']==='Zavrseno'){Sesija::postaviPoruku('Završeno iznajmljivanje se ne može menjati.','greska');header('Location: index.php?stranica=iznajmljivanje-detalji&id='.$id);exit;}$v=new VoziloRepozitorijum();$k=new KlijentRepozitorijum();$klijenti=$k->dajSve();$trenutniId=array_map(fn($s)=>(int)$s['VoziloID'],$zapis['Stavke']??[]);$vozila=$v->dajSlobodna();foreach(($zapis['Stavke']??[]) as $s)if(!array_filter($vozila,fn($x)=>(int)$x['ID']===(int)$s['VoziloID'])){$postojeci=$v->dajPoId((int)$s['VoziloID']);if($postojeci)$vozila[]=$postojeci;}$greska='';if($_SERVER['REQUEST_METHOD']==='POST'){$kid=(int)($_POST['klijentId']??0);$od=$_POST['datumOd']??'';$do=$_POST['datumDo']??'';$iz=$_POST['vozila']??[];if($kid<1||!$k->dajPoId($kid))$greska='Izaberite postojećeg klijenta.';if(!$greska)$greska=Validacija::datumOpseg($od,$do)??'';if(!$greska&&!$iz)$greska='Izaberite najmanje jedno vozilo.';if(!$greska)try{$klijent=$k->dajPoId($kid);$iznajmljivanje=new Iznajmljivanje($id,$klijent,$od,$do,'Aktivno');foreach($iz as $vid){$vozilo=$v->dajPoId((int)$vid);if(!$vozilo)throw new Exception('Izabrano vozilo nije pronađeno.');$iznajmljivanje->dodajStavku(new StavkaIznajmljivanja(null,$vozilo,$iznajmljivanje->brojDana(),$vozilo->cenaPoDanu,$iznajmljivanje->brojDana()*$vozilo->cenaPoDanu));}$repo->izmeni($iznajmljivanje,Sesija::korisnik()['Mejl']??'');$this->log('Izmena','Iznajmljivanje',$id,'Izmenjen ugovor');Sesija::postaviPoruku('Iznajmljivanje je uspešno izmenjeno.');header('Location: index.php?stranica=iznajmljivanje-detalji&id='.$id);exit;}catch(Throwable $e){$greska=$e->getMessage();}}require __DIR__.'/../pogledi/iznajmljivanja/izmeni.php'; }
    public function vrati(): void { Sesija::zahtevajPrijavu();if($_SERVER['REQUEST_METHOD']!=='POST')die('Nedozvoljena metoda.');$id=(int)($_POST['id']??0);$datum=$_POST['datumVracanja']??date('Y-m-d');$nap=trim($_POST['napomena']??'');try{$kas=(new IznajmljivanjeRepozitorijum())->zavrsi($id,$datum,$nap);$this->log('Vraćanje','Iznajmljivanje',$id,$kas>0?"Kašnjenje $kas dana":'Vraćeno na vreme');Sesija::postaviPoruku($kas>0?"Iznajmljivanje je završeno. Evidentirano kašnjenje: $kas dana.":'Iznajmljivanje je završeno i vozila su ponovo slobodna.');}catch(Throwable $e){Sesija::postaviPoruku($e->getMessage(),'greska');}header('Location: index.php?stranica=iznajmljivanje-detalji&id='.$id);exit; }
    public function obrisi(): void { Sesija::zahtevajPrijavu();if($_SERVER['REQUEST_METHOD']!=='POST')die('Nedozvoljena metoda.');$id=(int)($_POST['id']??0);(new IznajmljivanjeRepozitorijum())->obrisi($id);$this->log('Brisanje','Iznajmljivanje',$id);Sesija::postaviPoruku('Iznajmljivanje je obrisano.');header('Location: index.php?stranica=iznajmljivanja');exit; }
    public function stampaSpisak(): void { Sesija::zahtevajPrijavu();$filter=trim($_GET['filter']??'');$redovi=(new IznajmljivanjeRepozitorijum())->dajSve($filter);require __DIR__.'/../pogledi/stampa/spisak.php'; }
    public function stampaDokument(): void { Sesija::zahtevajPrijavu();$id=(int)($_GET['id']??0);$zapis=(new IznajmljivanjeRepozitorijum())->dajPoId($id);if(!$zapis)die('Dokument nije pronađen.');require __DIR__.'/../pogledi/stampa/dokument.php'; }
    private function log(string $a,string $e,?int $id,string $o=''): void { (new AktivnostRepozitorijum())->evidentiraj(Sesija::korisnik()['Mejl']??'sistem',$a,$e,$id,$o); }
}
