<?php

// Kontroler za administraciju korisnika i licni nalog.
require_once __DIR__.'/../servisi/Sesija.php';require_once __DIR__.'/../podaci/KorisnikRepozitorijum.php';require_once __DIR__.'/../podaci/AktivnostRepozitorijum.php';require_once __DIR__.'/../validacija/Validacija.php';
class KorisnikKontroler
{
    public function index(): void { Sesija::zahtevajAdmina();$redovi=(new KorisnikRepozitorijum())->dajSve();$poruka=Sesija::uzmiPoruku();require __DIR__.'/../pogledi/korisnici/index.php'; }
    public function dodaj(): void { Sesija::zahtevajAdmina();$repo=new KorisnikRepozitorijum();$greska='';$korisnik=$_POST;if($_SERVER['REQUEST_METHOD']==='POST'){$greska=$this->validiraj($_POST,$repo);if(!$greska){$id=$repo->dodaj(trim($_POST['ime']),trim($_POST['prezime']),trim($_POST['mejl']),$_POST['lozinka'],$_POST['uloga']);$this->log('Dodavanje','Korisnik',$id,'Dodat korisnik '.$_POST['mejl']);Sesija::postaviPoruku('Korisnik je dodat.');header('Location: index.php?stranica=korisnici');exit;}}require __DIR__.'/../pogledi/korisnici/forma.php'; }
    public function izmeni(): void { Sesija::zahtevajAdmina();$id=(int)($_GET['id']??0);$repo=new KorisnikRepozitorijum();$korisnik=$repo->dajPoId($id);if(!$korisnik)die('Korisnik nije pronađen.');$greska='';if($_SERVER['REQUEST_METHOD']==='POST'){$greska=$this->validiraj($_POST,$repo,$id,true);if(!$greska){$repo->izmeni($id,trim($_POST['ime']),trim($_POST['prezime']),trim($_POST['mejl']),$_POST['uloga'],isset($_POST['aktivan']));if(!empty($_POST['lozinka']))$repo->promeniLozinku($id,$_POST['lozinka']);$this->log('Izmena','Korisnik',$id,'Izmenjeni podaci korisnika');Sesija::postaviPoruku('Korisnik je izmenjen.');header('Location: index.php?stranica=korisnici');exit;}$korisnik = array_merge($korisnik->toArray(), $_POST);}require __DIR__.'/../pogledi/korisnici/forma.php'; }
    public function nalog(): void { Sesija::zahtevajPrijavu();$repo=new KorisnikRepozitorijum();$id=(int)Sesija::korisnik()['ID'];$korisnik=$repo->dajPoId($id);$greska='';$poruka=Sesija::uzmiPoruku();if($_SERVER['REQUEST_METHOD']==='POST'){$stara=$_POST['staraLozinka']??'';$nova=$_POST['novaLozinka']??'';$potvrda=$_POST['potvrdaLozinka']??'';if(!$repo->proveriLozinku($id,$stara))$greska='Trenutna lozinka nije ispravna.';elseif(strlen($nova)<6)$greska='Nova lozinka mora imati najmanje 6 karaktera.';elseif($nova!==$potvrda)$greska='Potvrda nove lozinke se ne poklapa.';else{$repo->promeniLozinku($id,$nova);$this->log('Promena lozinke','Korisnik',$id,'Korisnik je promenio svoju lozinku');Sesija::postaviPoruku('Lozinka je uspešno promenjena.');header('Location: index.php?stranica=moj-nalog');exit;}}require __DIR__.'/../pogledi/korisnici/nalog.php'; }
    public function aktivnosti(): void { Sesija::zahtevajAdmina();$redovi=(new AktivnostRepozitorijum())->dajSve();require __DIR__.'/../pogledi/aktivnosti/index.php'; }
    private function validiraj(array $p,KorisnikRepozitorijum $r,?int $id=null,bool $izmena=false): string { foreach(['ime'=>'Ime','prezime'=>'Prezime','mejl'=>'Mejl','uloga'=>'Uloga'] as $k=>$n)if($g=Validacija::obavezno($p[$k]??'',$n))return $g;if($g=Validacija::mejl(trim($p['mejl'])))return $g;if(!in_array($p['uloga'],['ADMIN','RADNIK'],true))return 'Uloga nije dozvoljena.';if(!$izmena&&strlen($p['lozinka']??'')<6)return 'Lozinka mora imati najmanje 6 karaktera.';if(!empty($p['lozinka'])&&strlen($p['lozinka'])<6)return 'Lozinka mora imati najmanje 6 karaktera.';if($r->postojiMejl(trim($p['mejl']),$id))return 'Korisnik sa tim mejlom već postoji.';return ''; }
    private function log(string $a,string $e,?int $id,string $o=''): void { (new AktivnostRepozitorijum())->evidentiraj(Sesija::korisnik()['Mejl']??'sistem',$a,$e,$id,$o); }
}
