<?php

// Kontroler za prikaz, dodavanje, izmenu i brisanje vozila.
require_once __DIR__.'/../servisi/Sesija.php';require_once __DIR__.'/../podaci/VoziloRepozitorijum.php';require_once __DIR__.'/../podaci/AktivnostRepozitorijum.php';require_once __DIR__.'/../validacija/Validacija.php';
class VoziloKontroler
{
    public function index(): void { Sesija::zahtevajPrijavu();$filter=trim($_GET['filter']??'');$status=trim($_GET['status']??'');$svi=(new VoziloRepozitorijum())->dajSve($filter,$status);$str=max(1,(int)($_GET['str']??1));$po=9;$ukupno=count($svi);$brojStr=max(1,(int)ceil($ukupno/$po));$str=min($str,$brojStr);$redovi=array_slice($svi,($str-1)*$po,$po);$poruka=Sesija::uzmiPoruku();require __DIR__.'/../pogledi/vozila/index.php'; }
    public function dodaj(): void { Sesija::zahtevajAdmina();$repo=new VoziloRepozitorijum();$greska='';$vozilo=$_POST;if($_SERVER['REQUEST_METHOD']==='POST'){$p=$this->podaci($_POST);$greska=$this->validiraj($p,$repo);if(!$greska){$id=$repo->dodaj($p);$this->log('Dodavanje','Vozilo',$id,$p['registracija']);Sesija::postaviPoruku('Vozilo je uspešno dodato.');header('Location: index.php?stranica=vozila');exit;}}require __DIR__.'/../pogledi/vozila/forma.php'; }
    public function izmeni(): void { Sesija::zahtevajAdmina();$id=(int)($_GET['id']??0);$repo=new VoziloRepozitorijum();$vozilo=$repo->dajPoId($id);if(!$vozilo)die('Vozilo nije pronađeno.');$greska='';if($_SERVER['REQUEST_METHOD']==='POST'){$p=$this->podaci($_POST);$greska=$this->validiraj($p,$repo,$id);if(!$greska){$repo->izmeni($id,$p);$this->log('Izmena','Vozilo',$id,$p['registracija']);Sesija::postaviPoruku('Podaci o vozilu su uspešno izmenjeni.');header('Location: index.php?stranica=vozila');exit;}$vozilo=array_merge($vozilo,array_combine(['Marka','Model','Registracija','Godiste','Gorivo','Menjac','BrojSedista','Kilometraza','Kategorija','CenaPoDanu','Status'],array_values($p)));}require __DIR__.'/../pogledi/vozila/forma.php'; }
    public function obrisi(): void { Sesija::zahtevajAdmina();if($_SERVER['REQUEST_METHOD']!=='POST')die('Nedozvoljena metoda.');$id=(int)($_POST['id']??0);try{(new VoziloRepozitorijum())->obrisi($id);$this->log('Brisanje','Vozilo',$id);Sesija::postaviPoruku('Vozilo je obrisano.');}catch(Throwable $e){Sesija::postaviPoruku('Vozilo se ne može obrisati jer se koristi u evidenciji iznajmljivanja.','greska');}header('Location: index.php?stranica=vozila');exit; }
    private function podaci(array $p): array { return ['marka'=>trim($p['marka']??''),'model'=>trim($p['model']??''),'registracija'=>strtoupper(trim($p['registracija']??'')),'godiste'=>(int)($p['godiste']??0),'gorivo'=>$p['gorivo']??'','menjac'=>$p['menjac']??'','brojSedista'=>(int)($p['brojSedista']??0),'kilometraza'=>(int)($p['kilometraza']??0),'kategorija'=>$p['kategorija']??'','cenaPoDanu'=>(float)str_replace(',','.',(string)($p['cenaPoDanu']??0)),'status'=>$p['status']??'Slobodno']; }
    private function validiraj(array $p,VoziloRepozitorijum $r,?int $id=null): string { if(strlen($p['marka'])<2||strlen($p['model'])<1)return 'Marka i model su obavezni.';if(!preg_match('/^[A-ZČĆŽŠĐ0-9\- ]{4,20}$/u',$p['registracija']))return 'Registracija nije u ispravnom formatu.';if($r->postojiRegistracija($p['registracija'],$id))return 'Vozilo sa tom registracijom već postoji.';$g=(int)date('Y');if($p['godiste']<1950||$p['godiste']>$g+1)return 'Godište vozila nije ispravno.';if(!in_array($p['gorivo'],['Benzin','Dizel','Hibrid','Električni'],true))return 'Gorivo nije dozvoljeno.';if(!in_array($p['menjac'],['Manuelni','Automatski'],true))return 'Menjač nije dozvoljen.';if($p['brojSedista']<1||$p['brojSedista']>60)return 'Broj sedišta nije ispravan.';if($p['kilometraza']<0)return 'Kilometraža ne može biti negativna.';if(!in_array($p['kategorija'],['Ekonomična','Kompakt','Limuzina','SUV','Karavan','Kombi','Premium'],true))return 'Kategorija nije dozvoljena.';if($p['cenaPoDanu']<=0)return 'Cena mora biti veća od nule.';if(!in_array($p['status'],['Slobodno','Iznajmljeno','Servis','Nedostupno'],true))return 'Status nije dozvoljen.';return ''; }
    private function log(string $a,string $e,?int $id,string $o=''): void { (new AktivnostRepozitorijum())->evidentiraj(Sesija::korisnik()['Mejl']??'sistem',$a,$e,$id,$o); }
}
