<?php
require_once __DIR__ . '/BazniRepozitorijum.php';
class IznajmljivanjeRepozitorijum extends BazniRepozitorijum
{
    public function dajSve(string $filter='',array $f=[]): array {
        $sql='SELECT p.* FROM dbo.PregledIznajmljivanja p WHERE 1=1';$p=[];
        if($filter!==''){$q="%$filter%";$sql.=" AND (Ime+' '+Prezime LIKE ? OR Mejl LIKE ? OR Status LIKE ? OR CAST(ID AS NVARCHAR(20)) LIKE ?)";array_push($p,$q,$q,$q,$q);}
        if(!empty($f['status'])&&in_array($f['status'],['Aktivno','Zavrseno'],true)){$sql.=' AND Status=?';$p[]=$f['status'];}
        if(!empty($f['klijentId'])){$sql.=' AND KlijentID=?';$p[]=(int)$f['klijentId'];}
        if(!empty($f['datumOd'])){$sql.=' AND DatumOd>=?';$p[]=$f['datumOd'];}
        if(!empty($f['datumDo'])){$sql.=' AND DatumDo<=?';$p[]=$f['datumDo'];}
        if(!empty($f['voziloId'])){$sql.=' AND EXISTS(SELECT 1 FROM dbo.StavkeIznajmljivanja s WHERE s.IznajmljivanjeID=p.ID AND s.VoziloID=?)';$p[]=(int)$f['voziloId'];}
        if(isset($f['minCena'])&&$f['minCena']!==''){$sql.=' AND UkupnaCena>=?';$p[]=(float)$f['minCena'];}
        if(isset($f['maxCena'])&&$f['maxCena']!==''){$sql.=' AND UkupnaCena<=?';$p[]=(float)$f['maxCena'];}
        return $this->izvrsiUpit($sql.' ORDER BY ID DESC',$p);
    }
    public function dajPoId(int $id): ?array { $g=$this->izvrsiUpit('SELECT i.*,k.Ime,k.Prezime,k.Mejl,k.Telefon,k.BrojDokumenta FROM dbo.Iznajmljivanja i JOIN dbo.Klijenti k ON k.ID=i.KlijentID WHERE i.ID=?',[$id]);if(!$g)return null;$g=$g[0];$g['Stavke']=$this->izvrsiUpit('SELECT s.*,v.Marka,v.Model,v.Registracija,v.Godiste,v.Gorivo,v.Menjac,v.Kategorija FROM dbo.StavkeIznajmljivanja s JOIN dbo.Vozila v ON v.ID=s.VoziloID WHERE s.IznajmljivanjeID=? ORDER BY s.ID',[$id]);return $g; }
    public function dodaj(int $klijentId,string $od,string $do,array $vozila,string $korisnik=''): int { if(!$vozila)throw new Exception('Mora biti izabrano najmanje jedno vozilo.');$this->konekcija->beginTransaction();try{$q=$this->konekcija->prepare("INSERT INTO dbo.Iznajmljivanja(KlijentID,DatumOd,DatumDo,Status,UkupnaCena,KreiraoKorisnik) OUTPUT INSERTED.ID VALUES(?,?,?,N'Aktivno',0,?)");$q->execute([$klijentId,$od,$do,$korisnik]);$id=(int)$q->fetchColumn();$d=max(1,(int)((strtotime($do)-strtotime($od))/86400)+1);$u=0;foreach($vozila as $vid){$q=$this->konekcija->prepare('SELECT * FROM dbo.Vozila WITH(UPDLOCK,ROWLOCK) WHERE ID=?');$q->execute([(int)$vid]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||$v['Status']!=='Slobodno')throw new Exception('Jedno od vozila više nije slobodno.');$iz=$d*(float)$v['CenaPoDanu'];$this->izvrsiKomandu('INSERT INTO dbo.StavkeIznajmljivanja(IznajmljivanjeID,VoziloID,BrojDana,CenaPoDanu,Iznos) VALUES(?,?,?,?,?)',[$id,(int)$vid,$d,$v['CenaPoDanu'],$iz]);$this->izvrsiKomandu("UPDATE dbo.Vozila SET Status=N'Iznajmljeno' WHERE ID=?",[(int)$vid]);$u+=$iz;}$this->izvrsiKomandu('UPDATE dbo.Iznajmljivanja SET UkupnaCena=? WHERE ID=?',[$u,$id]);$this->konekcija->commit();return $id;}catch(Throwable $e){if($this->konekcija->inTransaction())$this->konekcija->rollBack();throw $e;} }
    public function izmeni(int $id,int $klijentId,string $od,string $do,array $vozila,string $korisnik=''): void { $z=$this->dajPoId($id);if(!$z||$z['Status']==='Zavrseno')throw new Exception('Završeno iznajmljivanje se ne može menjati.');$this->konekcija->beginTransaction();try{$st=$this->izvrsiUpit('SELECT VoziloID FROM dbo.StavkeIznajmljivanja WHERE IznajmljivanjeID=?',[$id]);foreach($st as $s)$this->izvrsiKomandu("UPDATE dbo.Vozila SET Status=N'Slobodno' WHERE ID=?",[$s['VoziloID']]);$this->izvrsiKomandu('DELETE FROM dbo.StavkeIznajmljivanja WHERE IznajmljivanjeID=?',[$id]);$this->izvrsiKomandu('UPDATE dbo.Iznajmljivanja SET KlijentID=?,DatumOd=?,DatumDo=?,UkupnaCena=0,IzmenioKorisnik=? WHERE ID=?',[$klijentId,$od,$do,$korisnik,$id]);$d=max(1,(int)((strtotime($do)-strtotime($od))/86400)+1);$u=0;foreach($vozila as $vid){$q=$this->konekcija->prepare('SELECT * FROM dbo.Vozila WITH(UPDLOCK,ROWLOCK) WHERE ID=?');$q->execute([(int)$vid]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||$v['Status']!=='Slobodno')throw new Exception('Izabrano vozilo nije dostupno.');$iz=$d*(float)$v['CenaPoDanu'];$this->izvrsiKomandu('INSERT INTO dbo.StavkeIznajmljivanja(IznajmljivanjeID,VoziloID,BrojDana,CenaPoDanu,Iznos) VALUES(?,?,?,?,?)',[$id,(int)$vid,$d,$v['CenaPoDanu'],$iz]);$this->izvrsiKomandu("UPDATE dbo.Vozila SET Status=N'Iznajmljeno' WHERE ID=?",[(int)$vid]);$u+=$iz;}$this->izvrsiKomandu('UPDATE dbo.Iznajmljivanja SET UkupnaCena=? WHERE ID=?',[$u,$id]);$this->konekcija->commit();}catch(Throwable $e){if($this->konekcija->inTransaction())$this->konekcija->rollBack();throw $e;} }
    public function zavrsi(int $id,string $datum,string $napomena=''): int { $z=$this->dajPoId($id);if(!$z)throw new Exception('Iznajmljivanje nije pronađeno.');if($z['Status']==='Zavrseno')throw new Exception('Iznajmljivanje je već završeno.');if(strtotime($datum)<strtotime($z['DatumOd']))throw new Exception('Datum vraćanja ne može biti pre datuma preuzimanja.');$kas=max(0,(int)((strtotime($datum)-strtotime($z['DatumDo']))/86400));$this->konekcija->beginTransaction();try{$this->izvrsiKomandu("UPDATE dbo.Iznajmljivanja SET Status=N'Zavrseno',DatumVracanja=?,KasnjenjeDana=?,NapomenaVracanja=? WHERE ID=?",[$datum,$kas,$napomena,$id]);$this->izvrsiKomandu("UPDATE v SET Status=N'Slobodno' FROM dbo.Vozila v JOIN dbo.StavkeIznajmljivanja s ON s.VoziloID=v.ID WHERE s.IznajmljivanjeID=? AND v.Status=N'Iznajmljeno'",[$id]);$this->konekcija->commit();return $kas;}catch(Throwable $e){if($this->konekcija->inTransaction())$this->konekcija->rollBack();throw $e;} }
    public function dajStatistiku(): array { $r=$this->izvrsiUpit("SELECT COUNT(*) Ukupno,SUM(CASE WHEN Status=N'Aktivno' THEN 1 ELSE 0 END) Aktivna,SUM(CASE WHEN Status=N'Zavrseno' THEN 1 ELSE 0 END) Zavrsena FROM dbo.Iznajmljivanja");$s=$r[0]??[];return ['ukupno'=>(int)($s['Ukupno']??0),'aktivna'=>(int)($s['Aktivna']??0),'zavrsena'=>(int)($s['Zavrsena']??0)]; }
    public function dajPoslednja(int $n=5): array { $n=max(1,min(10,$n));return $this->izvrsiUpit("SELECT TOP $n * FROM dbo.PregledIznajmljivanja ORDER BY ID DESC"); }
    public function obrisi(int $id): void { $this->izvrsiProceduru('dbo.ObrisiIznajmljivanje',[$id]); }
}
